
# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://124.71.104.26:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:p6spy:mysql://127.0.0.1:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root


  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
    suffix: .ftl

  redis:
    host: myhost
  jpa:
    show-sql: true

  elasticsearch:
    rest:
      uris: http://myhost:9200

  rabbitmq:
    host: myhost
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

file:
  upload:
    dir: ${user.dir}/upload

im:
  server:
    port: 9326
